// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RecipeFormController from "./recipe_form_controller"
application.register("recipe-form", RecipeFormController)

import SectionController from "./section_controller"
application.register("section", SectionController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)
